/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBuOo2MRpudlxaxjNV6yMBKzCTNHyOdaA',
    appId: '1:377092431507:web:3a59f5b169d1d13a17b766',
    messagingSenderId: '377092431507',
    projectId: 'spotify000',
    authDomain: 'spotify000.firebaseapp.com',
    storageBucket: 'spotify000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCE0OpFY0YgMBG_VcWGZEQCjia3RN7L8',
    appId: '1:377092431507:android:ee4c24690603dbf917b766',
    messagingSenderId: '377092431507',
    projectId: 'spotify000',
    storageBucket: 'spotify000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE7GjVpNjg2vHuf2k2YwWz7OtIRhwVybI',
    appId: '1:377092431507:ios:465a97acbc9f226017b766',
    messagingSenderId: '377092431507',
    projectId: 'spotify000',
    storageBucket: 'spotify000.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE7GjVpNjg2vHuf2k2YwWz7OtIRhwVybI',
    appId: '1:377092431507:ios:465a97acbc9f226017b766',
    messagingSenderId: '377092431507',
    projectId: 'spotify000',
    storageBucket: 'spotify000.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBuOo2MRpudlxaxjNV6yMBKzCTNHyOdaA',
    appId: '1:377092431507:web:6727a5ea9d878a6317b766',
    messagingSenderId: '377092431507',
    projectId: 'spotify000',
    authDomain: 'spotify000.firebaseapp.com',
    storageBucket: 'spotify000.appspot.com',
  );

}*/